name  'hetzner-roundcube'
version '0.1.9'
source 'git://github.com/hetznerZA/hetzner-roundcube.git'
author 'Hetzner'
license 'Apache License, Version 2.0'
summary 'Roundcube webmail resource types'
description 'This module provides the necessary classes to install a configurable roundcube webmail service.'

dependency 'puppetlabs/apache', '>= 0.10.0'
dependency 'puppetlabs/inifile', '>= 1.0.0'
dependency 'puppetlabs/postgresql', '>= 3.3.0'
dependency 'puppetlabs/apt', '>= 1.4.0'
