name  'hetzner-roundcube'
version '0.1.27'
source 'git://github.com/hetznerZA/hetzner-roundcube.git'
author 'Hetzner'
license 'Apache License, Version 2.0'
summary 'Roundcube webmail resource types'
description 'This module provides the necessary classes to install a configurable roundcube webmail service.'

dependency 'puppetlabs/apache', '>= 1.2.0'
dependency 'puppetlabs/inifile', '>= 1.2.0'
dependency 'puppetlabs/postgresql', '>= 3.3.0'
dependency 'puppetlabs/apt', '>= 1.6.0 < 1.9.0'
dependency 'puppetlabs/stdlib', '>= 4.6.0'
