name  'hetzner-roundcube'
version '1.2.1'
source 'git://github.com/hetznerZA/hetzner-roundcube.git'
author 'Hetzner'
license 'Apache License, Version 2.0'
summary 'Roundcube webmail resource types'
description 'This module provides the necessary classes to install a configurable roundcube webmail service.'

dependency 'puppetlabs/apache', '>= 2.0.0'
dependency 'puppetlabs/inifile', '>= 1.6.0'
dependency 'puppetlabs/postgresql', '>= 5.2.0'
dependency 'puppetlabs/apt', '>= 4.5.0'
dependency 'puppetlabs/stdlib', '>= 4.25.0'
